# Generated by Django 5.1.1 on 2024-10-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_quantity_bookrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrecord',
            old_name='status',
            new_name='action_type',
        ),
    ]
